# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
    ]
