# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170321_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_checkedin',
            new_name='is_checked_in',
        ),
    ]
