# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
